### ISSUE TITLE
No class-fixed. json file found

### ISSUE THREAD

**Issue by Miraitwo** [cheeseBG/meta-transformer-amc#4]
Hello author, while running the code, I did not find the class-fixed. json file in the RML2018 folder. Could you please provide it? Thank you very much

**Comment by cheeseBG** [comment]
This JSON file is included when you download the RML2018.01A dataset. If it is not included, you can download it from the Google Drive URL below.

https://drive.google.com/file/d/124mcAvxiHX93h6ufSyiL_Z8y-2E4WLvJ/view?usp=sharing

**Comment by Miraitwo** [comment]
Thank you very much for the author's reply. Due to my carelessness, I did not notice the classes-fixed. json file included in the dataset downloaded from the official website. Once again, thank you very much for the author's sharing and reply

**Comment by cheeseBG** [comment]
I'm glad it was helpful. I will now close this issue.
